#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:00:00

set -e
set -x

mkdir -p trk

time singularity exec -e docker://brainlife/dipy:1.1.1 ./wmc_to_trk.py

#create product.json
#echo -e "{\n\t\"trk\":" > ./product.json
#cat ./trk/info.json >> ./product.json
#echo -e "\n}" >> ./product.json
